Traceback (most recent call last):
  File "/home/tjhunter/.cache/pypoetry/virtualenvs/climate-trace-nO4nxH9g-py3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/tjhunter/.cache/pypoetry/virtualenvs/climate-trace-nO4nxH9g-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/tjhunter/.cache/pypoetry/virtualenvs/climate-trace-nO4nxH9g-py3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/tjhunter/.cache/pypoetry/virtualenvs/climate-trace-nO4nxH9g-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/tjhunter/.cache/pypoetry/virtualenvs/climate-trace-nO4nxH9g-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/tjhunter/.cache/pypoetry/virtualenvs/climate-trace-nO4nxH9g-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
year = 2023
gas = CO2E_100YR
gas_conf = "conf_emissions_quantity"
c_gas_conf = C(gas_conf)
sdf_gy = ct.read_source_emissions(year=year, p="/tmp").filter(c_gas == gas) # TODO
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 5[0m
[1;32m      3[0m gas_conf [38;5;241m=[39m [38;5;124m"[39m[38;5;124mconf_emissions_quantity[39m[38;5;124m"[39m
[1;32m      4[0m c_gas_conf [38;5;241m=[39m C(gas_conf)
[0;32m----> 5[0m sdf_gy [38;5;241m=[39m [43mct[49m[38;5;241;43m.[39;49m[43mread_source_emissions[49m[43m([49m[43myear[49m[38;5;241;43m=[39;49m[43myear[49m[43m,[49m[43m [49m[43mp[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43m/tmp[39;49m[38;5;124;43m"[39;49m[43m)[49m[38;5;241m.[39mfilter(c_gas [38;5;241m==[39m gas) [38;5;66;03m# TODO[39;00m

[0;31mTypeError[0m: read_source_emissions() missing 1 required positional argument: 'gas'

